In [36]:
import pandas as pd
import numpy as np
import timeit

In [37]:
# 数据集处理函数
def data_process(data_set, feature_size):
    total=[]
    dict_1={}
    for i in range(feature_size):
        a=str(i+1)
        dict_1[a]=0.0
    total.append(dict_1)
    for i in range(len(data_set)):
        data_sep=[]
        data_sep.append(data_set[i][0].split(' '))
        data_sep[0] = list(filter(None, data_sep[0]))
        new_dict={}
        new_dict['label']=float(data_sep[0][0])
        for j in range(len(data_sep[0])-1):
            a=[]
            a.append(data_sep[0][j+1].split(':'))
            new_dict[a[0][0]]=float(a[0][1])
        total.append(new_dict)
    df=pd.DataFrame(total).fillna(0.0)
    df=df.drop(index=(df.loc[(df['label']==0.0)].index))
    return df

In [38]:
# 处理训练集
mnist_tr ='mnist.scale'
mnist_tr_file = open(mnist_tr,'r')
lines = mnist_tr_file.readlines()

mnist_tr_data=[]
for line in lines:
    temp1=line.strip('\n')
    temp2=temp1.split('\t')
    mnist_tr_data.append(temp2)


mnist_tr_data_process = data_process(mnist_tr_data, 784)
mnist_tr_data_process

,1,2,3,4,5,6,7,8,9,10,...,776,777,778,779,780,781,782,783,784,label
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9.0
6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59996,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8.0
59997,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0
59998,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0
59999,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.0
60000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8.0

In [39]:
# 处理测试集
mnist_t ='mnist.scale.t'
mnist_t_file = open(mnist_t,'r')
lines = mnist_t_file.readlines()

mnist_t_data=[]
for line in lines:
    temp1=line.strip('\n')
    temp2=temp1.split('\t')
    mnist_t_data.append(temp2)


mnist_t_data_process = data_process(mnist_t_data, 784)
mnist_t_data_process

,1,2,3,4,5,6,7,8,9,10,...,776,777,778,779,780,781,782,783,784,label
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0
6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9996,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0
9997,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0
9998,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0
9999,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0
10000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.0

In [40]:
mnist_t_data_process_nolabel = mnist_t_data_process.drop('label',axis=1)

# Test for Search speed

### First test for ball-tree

In [41]:
# Now we ues the KNN balltree to test the time for Search
# We use the default parameters
import numpy as np
from sklearn.neighbors import BallTree

# 1.Euclidean  2.leaf_sizepositive:default=40
start=timeit.default_timer()
tree = BallTree(mnist_t_data_process_nolabel, leaf_size=2)   
stop=timeit.default_timer()
build_tree_time = stop-start
print("The time cost on build the tree")
print(build_tree_time)

print("Now we start to test a search in this ball-tree")
print("We select the index=2 datapoint , to find its 3 neighbors ")
start=timeit.default_timer()
dist, ind = tree.query(mnist_t_data_process_nolabel.iloc[[2]], k=4)
stop=timeit.default_timer()
print("We find the 3 cloest neighbors (the result include the data themself), the index are below ")
print(ind)  # indices of 3 closest neighbors
print("We find the 3 cloest neighbors , the distance are below ")
print(dist)  # distances to 3 closest neighbors
print("The search time cost is that ")
run_time = stop - start
print(run_time)

The time cost on build the tree
1.3839822999998432
Now we start to test a search in this ball-tree
We select the index=2 datapoint , to find its 3 neighbors
We find the 3 cloest neighbors (the result include the data themself), the index are below
[[   2  187 3501 3075]]
We find the 3 cloest neighbors , the distance are below
[[0.         1.41179161 1.64915792 1.65407443]]
The search time cost is that
0.01366390000021056

In [42]:
tree = BallTree(mnist_t_data_process_nolabel, leaf_size=2) 
every_time = []
for i in range(5000):
    start=timeit.default_timer()
    dist, ind = tree.query(mnist_t_data_process_nolabel.iloc[[i]], k=4)
    stop=timeit.default_timer()
    time_cost = stop- start
    every_time.append(time_cost)

In [44]:
Search_mean_time_balltree = np.mean(every_time)
Search_mean_time_balltree

0.017521292600001105

### Second test for KD-tree

In [45]:
# Now we ues the KNN kdtree to test the time for Search
# We use the default parameters
import numpy as np
from sklearn.neighbors import KDTree

# 1.Euclidean  2.leaf_sizepositive:default=40
start=timeit.default_timer()
tree = KDTree(mnist_t_data_process_nolabel, leaf_size=2)   
stop=timeit.default_timer()
build_tree_time = stop-start
print("The time cost on build the tree")
print(build_tree_time)

print("Now we start to test a search in this kd-tree")
print("We select the index=2 datapoint , to find its 3 neighbors ")
start=timeit.default_timer()
dist, ind = tree.query(mnist_t_data_process_nolabel.iloc[[2]], k=4)
stop=timeit.default_timer()
print("We find the 3 cloest neighbors (the result include the data themself), the index are below ")
print(ind)  # indices of 3 closest neighbors
print("We find the 3 cloest neighbors , the distance are below ")
print(dist)  # distances to 3 closest neighbors
print("The search time cost is that ")
run_time = stop - start
print(run_time)

The time cost on build the tree
2.292370299999675
Now we start to test a search in this kd-tree
We select the index=2 datapoint , to find its 3 neighbors
We find the 3 cloest neighbors (the result include the data themself), the index are below
[[   2  187 3501 3075]]
We find the 3 cloest neighbors , the distance are below
[[0.         1.41179161 1.64915792 1.65407443]]
The search time cost is that
0.05079870000008668

In [46]:
tree = KDTree(mnist_t_data_process_nolabel, leaf_size=2) 
every_time = []
for i in range(5000):
    start=timeit.default_timer()
    dist, ind = tree.query(mnist_t_data_process_nolabel.iloc[[i]], k=4)
    stop=timeit.default_timer()
    time_cost = stop- start
    every_time.append(time_cost)

In [47]:
Search_mean_time_kdtree = np.mean(every_time)
Search_mean_time_kdtree

0.05615169207998733

The search speed of balltree is significant fast than kdtree!

# Test for classify

In [48]:
# Now we test the Classifiy on the KNN BallTree

In [49]:
X = mnist_tr_data_process.drop('label',axis=1)
X

,1,2,3,4,5,6,7,8,9,10,...,775,776,777,778,779,780,781,782,783,784
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59996,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
59997,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
59998,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
59999,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
60000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [50]:
Y = mnist_tr_data_process['label']
Y

1        5.0
3        4.0
4        1.0
5        9.0
6        2.0
        ...
59996    8.0
59997    3.0
59998    5.0
59999    6.0
60000    8.0
Name: label, Length: 54077, dtype: float64

In [51]:
test_X = mnist_t_data_process.drop('label',axis=1)
test_X

,1,2,3,4,5,6,7,8,9,10,...,775,776,777,778,779,780,781,782,783,784
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9996,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9997,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9998,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9999,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [55]:
# Now we test the Classifiy on the KNN balltree
# Parameter:
#  n_neighbors=3
#  algorithm:balltree
#  leaf_sizeint, default=30
#  pint, default=2 ,it means we used the euclidean_distance
from sklearn.neighbors import KNeighborsClassifier
start=timeit.default_timer()
neigh = KNeighborsClassifier(n_neighbors=3,algorithm ='ball_tree')
neigh.fit(X, Y)
predict_result = neigh.predict(test_X)
stop=timeit.default_timer()
run_classfy_time_balltree = stop - start
print("run_classfy_time_balltree")
print(run_classfy_time_balltree)

run_classfy_time_balltree
436.66509600000063

In [57]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report
y_true = mnist_t_data_process['label'].values
y_pred = predict_result
accuracy_score(y_true, y_pred)
# The accuracy

0.9700665188470067

In [58]:
print(classification_report(y_true, y_pred))

              precision    recall  f1-score   support

         1.0       0.96      1.00      0.98      1135
         2.0       0.98      0.97      0.98      1032
         3.0       0.96      0.97      0.96      1010
         4.0       0.97      0.97      0.97       982
         5.0       0.97      0.97      0.97       892
         6.0       0.98      0.99      0.98       958
         7.0       0.97      0.96      0.96      1028
         8.0       0.99      0.94      0.97       974
         9.0       0.96      0.96      0.96      1009

    accuracy                           0.97      9020
   macro avg       0.97      0.97      0.97      9020
weighted avg       0.97      0.97      0.97      9020

In [59]:
# Now we test the Classifiy on the KNN kdTree
# Parameter:
#  n_neighbors=3
#  algorithm:kdtree
#  leaf_sizeint, default=30
#  pint, default=2 ,it means we used the euclidean_distance
from sklearn.neighbors import KNeighborsClassifier
start=timeit.default_timer()
neigh = KNeighborsClassifier(n_neighbors=3,algorithm ='kd_tree')
neigh.fit(X, Y)
predict_result = neigh.predict(test_X)
stop=timeit.default_timer()
run_classfy_time_kdtree = stop - start
print("run_classfy_time_kdtree")
print(run_classfy_time_kdtree)

run_classfy_time_kdtree
526.8561570000002

In [60]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report
y_true = mnist_t_data_process['label'].values
y_pred = predict_result
accuracy_score(y_true, y_pred)
# The accuracy

0.9700665188470067

In [65]:
accuracy = accuracy_score(y_true, y_pred)

In [63]:
print(classification_report(y_true, y_pred))

              precision    recall  f1-score   support

         1.0       0.96      1.00      0.98      1135
         2.0       0.98      0.97      0.98      1032
         3.0       0.96      0.97      0.96      1010
         4.0       0.97      0.97      0.97       982
         5.0       0.97      0.97      0.97       892
         6.0       0.98      0.99      0.98       958
         7.0       0.97      0.96      0.96      1028
         8.0       0.99      0.94      0.97       974
         9.0       0.96      0.96      0.96      1009

    accuracy                           0.97      9020
   macro avg       0.97      0.97      0.97      9020
weighted avg       0.97      0.97      0.97      9020

In [67]:
result = pd.DataFrame(columns=['Classify time','Classify Accuracy','Search means time'])
result.loc['balltree'] = [run_classfy_time_balltree,accuracy,Search_mean_time_balltree]
result.loc['kdtree'] = [run_classfy_time_kdtree,accuracy,Search_mean_time_kdtree]

The Kdtree and balltree in the MNIST dataset

In [68]:
result

          Classify time  Classify Accuracy  Search means time
balltree     436.665096           0.970067           0.017521
kdtree       526.856157           0.970067           0.056152